versions:
  "1.29":
    components:
      kubernetes: "1.29.10"
      kubelet: "1.29.10"
      coredns: "v1.11.1"
      vpc-cni: "v1.18.2"
      kube-proxy: "1.29.10"
  "1.30":
    components:
      kubernetes: "1.30.6"
      kubelet: "1.30.6"
      coredns: "v1.11.1"
      vpc-cni: "v1.19.0"
      kube-proxy: "1.30.6"
  "1.31":
    components:
      kubernetes: "1.31.2"
      kubelet: "1.31.2"
      coredns: "v1.11.3"
      vpc-cni: "v1.19.2"
      kube-proxy: "1.31.2"
