versions:
  "1.29":
    components:
      kubernetes: "1.29.10-gke.1046000"
      kubelet: "1.29.10-gke.1046000"
      coredns: "1.11.1"
      kube-proxy: "1.29.10-gke.1046000"
  "1.30":
    components:
      kubernetes: "1.30.6-gke.1125000"
      kubelet: "1.30.6-gke.1125000"
      coredns: "1.11.1"
      kube-proxy: "1.30.6-gke.1125000"
  "1.31":
    components:
      kubernetes: "1.31.1-gke.1064000"
      kubelet: "1.31.1-gke.1064000"
      coredns: "1.11.3"
      kube-proxy: "1.31.1-gke.1064000"
