versions:
  "1.29":
    components:
      rke2: "v1.29.10+rke2r1"
      kubernetes: "1.29.10"
      coredns: "v1.11.1"
      etcd: "3.5.16"
  "1.30":
    components:
      rke2: "v1.30.6+rke2r1"
      kubernetes: "1.30.6"
      coredns: "v1.11.1"
      etcd: "3.5.16"
  "1.31":
    components:
      rke2: "v1.31.2+rke2r1"
      kubernetes: "1.31.2"
      coredns: "v1.11.3"
      etcd: "3.5.17"
